import type { Channel, DirectMessage, Message, User } from "./types";

export const CURRENT_USER_ID = "u1";

export const users: User[] = [
  {
    id: "u1",
    name: "Brandon Peralta",
    displayName: "bperalta",
    avatar: "BP",
    presence: "active",
    status: "On shift · Bay-2",
    title: "Remote Fleet Operator · ZX-OP-10481",
  },
  {
    id: "u2",
    name: "Sarah Okonkwo",
    displayName: "sokonkwo",
    avatar: "SO",
    presence: "active",
    status: "Working INC-8842",
    title: "Remote Fleet Operator · Bay-2",
  },
  {
    id: "u3",
    name: "James Liu",
    displayName: "jliu",
    avatar: "JL",
    presence: "active",
    status: "Route 12 coverage",
    title: "Remote Fleet Operator · Bay-1",
  },
  {
    id: "u4",
    name: "M. Chen",
    displayName: "mchen",
    avatar: "MC",
    presence: "away",
    status: "On site · Kato Rd",
    title: "Field Tech",
  },
  {
    id: "u5",
    name: "Priya Nair",
    displayName: "pnair",
    avatar: "PN",
    presence: "active",
    status: "Primary on-call",
    title: "Fleet Engineer",
  },
  {
    id: "u6",
    name: "Depot Ops",
    displayName: "depot",
    avatar: "DO",
    presence: "active",
    status: "Foster City lead",
    title: "Depot Operations",
  },
  {
    id: "u7",
    name: "PagerDuty",
    displayName: "pagerduty",
    avatar: "PD",
    presence: "active",
    title: "Alert bot",
  },
];

export const channels: Channel[] = [
  {
    id: "c-fleet-ops",
    name: "fleet-ops-bay",
    description: "Primary remote ops floor — Bay-1 / Bay-2 coverage",
    topic: "Live vehicle holds, assists, and bay-to-bay handoffs",
    isPrivate: false,
    memberIds: ["u1", "u2", "u3", "u5", "u6"],
    unread: 2,
  },
  {
    id: "c-field",
    name: "field-dispatch",
    description: "Field tech + depot coordination",
    topic: "Dispatch, lidar cal, charge slots, staged vehicles",
    isPrivate: false,
    memberIds: ["u1", "u2", "u4", "u6"],
    unread: 1,
  },
  {
    id: "c-eng",
    name: "eng-oncall",
    description: "Platform / telemetry / PagerDuty escalations",
    topic: "Priya Nair primary · Eng rotation B secondary",
    isPrivate: false,
    memberIds: ["u1", "u5", "u7"],
    unread: 1,
  },
  {
    id: "c-incidents",
    name: "incidents",
    description: "Active incident thread — ack, escalate, resolve",
    topic: "Open: INC-8842 · HD-4421",
    isPrivate: false,
    memberIds: ["u1", "u2", "u3", "u4", "u5"],
    unread: 0,
  },
  {
    id: "c-shift",
    name: "shift-handoff",
    description: "Day ↔ night operator handoff notes",
    topic: "Post metrics before clock-out",
    isPrivate: false,
    memberIds: ["u1", "u2", "u3", "u6"],
    unread: 0,
  },
  {
    id: "c-ops-private",
    name: "bay-2-leads",
    description: "Private Bay-2 lead channel",
    isPrivate: true,
    memberIds: ["u1", "u2"],
    unread: 0,
  },
];

export const directMessages: DirectMessage[] = [
  { id: "dm-u2", userId: "u2", unread: 1 },
  { id: "dm-u3", userId: "u3" },
  { id: "dm-u4", userId: "u4" },
  { id: "dm-u5", userId: "u5" },
  { id: "dm-u6", userId: "u6" },
];

const minutesAgo = (m: number) =>
  new Date(Date.now() - m * 60_000).toISOString();

export const initialMessages: Message[] = [
  {
    id: "m1",
    channelId: "c-fleet-ops",
    userId: "u3",
    text: "Route 12 running smooth. Mission loop on time — Ferry Building clear.",
    createdAt: minutesAgo(35),
    reactions: [{ emoji: "👍", userIds: ["u1", "u2"] }],
  },
  {
    id: "m2",
    channelId: "c-fleet-ops",
    userId: "u2",
    text: "ZX-1199 obstacle hold on Sunset — need eyes on front cam. INC-8842 open.",
    createdAt: minutesAgo(8),
    reactions: [{ emoji: "👀", userIds: ["u1", "u3"] }],
    replyCount: 2,
  },
  {
    id: "m3",
    channelId: "c-fleet-ops",
    userId: "u1",
    text: "Pulling surround cams now. Vehicle stationary — confirming clearance window.",
    createdAt: minutesAgo(6),
    reactions: [],
    threadId: "m2",
  },
  {
    id: "m4",
    channelId: "c-fleet-ops",
    userId: "u2",
    text: "Thanks — if >10 min escalate per Obstacle Hold SOP. Field standing by.",
    createdAt: minutesAgo(5),
    reactions: [],
    threadId: "m2",
  },
  {
    id: "m5",
    channelId: "c-fleet-ops",
    userId: "u1",
    text: "Bay-2 clocked in. Taking INC-8842 assist if needed.",
    createdAt: minutesAgo(2),
    reactions: [],
  },
  {
    id: "m6",
    channelId: "c-field",
    userId: "u4",
    text: "At Kato Rd on ZX-0721 lidar cal. Back in service ~2 hrs.",
    createdAt: minutesAgo(22),
    reactions: [{ emoji: "🛠️", userIds: ["u6"] }],
  },
  {
    id: "m7",
    channelId: "c-field",
    userId: "u6",
    text: "ZX-0915 (L3) charging — slot 4, 34% → est. ready 17:45 PST.",
    createdAt: minutesAgo(12),
    reactions: [],
  },
  {
    id: "m8",
    channelId: "c-field",
    userId: "u6",
    text: "ZX-1178 staged and ready for Route 14 assignment.",
    createdAt: minutesAgo(4),
    reactions: [{ emoji: "✅", userIds: ["u1"] }],
  },
  {
    id: "m9",
    channelId: "c-eng",
    userId: "u7",
    text: "ALERT: ZX-1134 telemetry gap > 15 min. Comms subsystem flagged. Ticket HD-4421.",
    createdAt: minutesAgo(18),
    reactions: [{ emoji: "🚨", userIds: ["u5"] }],
  },
  {
    id: "m10",
    channelId: "c-eng",
    userId: "u5",
    text: "Acknowledged. Checking VPN tunnel + last GPS. Will escalate if gap hits 20 min.",
    createdAt: minutesAgo(14),
    reactions: [],
    replyCount: 1,
  },
  {
    id: "m11",
    channelId: "c-eng",
    userId: "u1",
    text: "Last known: Mission Bay. Battery 41% — not critical yet.",
    createdAt: minutesAgo(11),
    reactions: [],
    threadId: "m10",
  },
  {
    id: "m12",
    channelId: "c-incidents",
    userId: "u2",
    text: "INC-8842 · ZX-1199 safety hold — obstacle detected · In Progress · assignee Sarah Okonkwo",
    createdAt: minutesAgo(40),
    reactions: [],
  },
  {
    id: "m13",
    channelId: "c-incidents",
    userId: "u5",
    text: "HD-4421 · ZX-1134 comms telemetry gap · Open · assignee IT / Eng on-call",
    createdAt: minutesAgo(20),
    reactions: [],
  },
  {
    id: "m14",
    channelId: "c-incidents",
    userId: "u6",
    text: "INC-8839 · ZX-0915 charge stall B4 intermittent · Resolved",
    createdAt: minutesAgo(90),
    reactions: [{ emoji: "✅", userIds: ["u1", "u2"] }],
  },
  {
    id: "m15",
    channelId: "c-shift",
    userId: "u3",
    text: "Morning handoff: 14 in service · 2 open incidents · Route 14 still unassigned (FLT-2108).",
    createdAt: minutesAgo(180),
    reactions: [{ emoji: "📋", userIds: ["u1", "u2"] }],
  },
  {
    id: "m16",
    channelId: "c-ops-private",
    userId: "u2",
    text: "Bay-2 density is high this afternoon — keep one operator free for remote assist.",
    createdAt: minutesAgo(50),
    reactions: [],
  },
  {
    id: "m17",
    channelId: "dm-u2",
    userId: "u2",
    text: "Can you take eyes on ZX-1199 front cam while I update INC-8842?",
    createdAt: minutesAgo(7),
    reactions: [],
  },
  {
    id: "m18",
    channelId: "dm-u5",
    userId: "u5",
    text: "If ZX-1134 gap continues, run Comms Loss Procedure — I can join the bridge.",
    createdAt: minutesAgo(13),
    reactions: [],
  },
  {
    id: "m19",
    channelId: "dm-u4",
    userId: "u4",
    text: "Need a tow slot cleared at Foster if lidar cal slips past 19:00.",
    createdAt: minutesAgo(25),
    reactions: [],
  },
];

export function getUser(id: string) {
  return users.find((u) => u.id === id);
}

export const workspace = {
  name: "Zoox Fleet Ops",
  initial: "Z",
  subtitle: "Foster City · Remote Ops",
};
